# Generated by Django 5.0.4 on 2024-04-23 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='[[{"figureNumber":10,"turnsMade":0},{"figureNumber":9},{"figureNumber":8},{"figureNumber":11},{"figureNumber":12,"turnsMade":0},{"figureNumber":8},{"figureNumber":9},{"figureNumber":10,"turnsMade":0}],[{"figureNumber":7,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":7,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":7,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":7,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":7,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":7,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":7,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":7,"turnsMade":0,"canBeBeatenAsideWithinTurn":0}],[{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0}],[{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0}],[{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0}],[{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0},{"figureNumber":0}],[{"figureNumber":1,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":1,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":1,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":1,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":1,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":1,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":1,"turnsMade":0,"canBeBeatenAsideWithinTurn":0},{"figureNumber":1,"turnsMade":0,"canBeBeatenAsideWithinTurn":0}],[{"figureNumber":4,"turnsMade":0},{"figureNumber":3},{"figureNumber":2},{"figureNumber":5},{"figureNumber":6,"turnsMade":0},{"figureNumber":2},{"figureNumber":3},{"figureNumber":4,"turnsMade":0}]]', max_length=1000)),
                ('playerTurn', models.CharField(default='player_white', max_length=30)),
                ('turnCount', models.IntegerField()),
                ('player1SecondsTime', models.IntegerField()),
                ('player2SecondsTime', models.IntegerField()),
                ('isGameOver', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_white', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_black', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
