# Generated by Django 5.0.4 on 2024-04-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='turnSecondsIncrease',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='turnCount',
            field=models.IntegerField(default=1),
        ),
    ]
