# Generated by Django 5.0.4 on 2024-04-23 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_service', '0002_chessgame_turnsecondsincrease_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_gamesetups', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_gamesetups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
